# Create mapping between community names and official Chicago community area IDs
community_map = {
    "ROGERS PARK": 1,
    "WEST RIDGE": 2,
    "UPTOWN": 3,
    "LINCOLN SQUARE": 4,
    "NORTH CENTER": 5,
    "LAKE VIEW": 6,
    "LINCOLN PARK": 7,
    "NEAR NORTH SIDE": 8,
    "EDISON PARK": 9,
    "NORWOOD PARK": 10,
    "JEFFERSON PARK": 11,
    "FOREST GLEN": 12,
    "NORTH PARK": 13,
    "ALBANY PARK": 14,
    "PORTAGE PARK": 15,
    "IRVING PARK": 16,
    "DUNNING": 17,
    "MONTCLARE": 18,
    "BELMONT CRAGIN": 19,
    "HERMOSA": 20,
    "AVONDALE": 21,
    "LOGAN SQUARE": 22,
    "HUMBOLDT PARK": 23,
    "WEST TOWN": 24,
    "AUSTIN": 25,
    "WEST GARFIELD PARK": 26,
    "EAST GARFIELD PARK": 27,
    "NEAR WEST SIDE": 28,
    "NORTH LAWNDALE": 29,
    "SOUTH LAWNDALE": 30,
    "LOWER WEST SIDE": 31,
    "LOOP": 32,
    "NEAR SOUTH SIDE": 33,
    "ARMOUR SQUARE": 34,
    "DOUGLAS": 35,
    "OAKLAND": 36,
    "FULLER PARK": 37,
    "GRAND BOULEVARD": 38,
    "KENWOOD": 39,
    "WASHINGTON PARK": 40,
    "HYDE PARK": 41,
    "WOODLAWN": 42,
    "SOUTH SHORE": 43,
    "CHATHAM": 44,
    "AVALON PARK": 45,
    "SOUTH CHICAGO": 46,
    "BURNSIDE": 47,
    "CALUMET HEIGHTS": 48,
    "ROSELAND": 49,
    "PULLMAN": 50,
    "SOUTH DEERING": 51,
    "EAST SIDE": 52,
    "WEST PULLMAN": 53,
    "RIVERDALE": 54,
    "HEGEWISCH": 55,
    "GARFIELD RIDGE": 56,
    "ARCHER HEIGHTS": 57,
    "BRIGHTON PARK": 58,
    "MCKINLEY PARK": 59,
    "BRIDGEPORT": 60,
    "NEW CITY": 61,
    "WEST ELSDON": 62,
    "GAGE PARK": 63,
    "CLEARING": 64,
    "WEST LAWN": 65,
    "CHICAGO LAWN": 66,
    "WEST ENGLEWOOD": 67,
    "ENGLEWOOD": 68,
    "GREATER GRAND CROSSING": 69,
    "ASHBURN": 70,
    "AUBURN GRESHAM": 71,
    "BEVERLY": 72,
    "WASHINGTON HEIGHTS": 73,
    "MOUNT GREENWOOD": 74,
    "MORGAN PARK": 75,
    "OHARE": 76,
    "EDGEWATER": 77
}

# Apply the mapping
acs["community_area_id"] = acs["Community Area"].map(community_map)

# Check if any community failed to map
missing_ids = acs["community_area_id"].isna().sum()
print("Unmapped communities:", missing_ids)

# Preview results
acs[["Community Area", "community_area_id", "community_type"]].head(10)